TestException1 risen
1

Catching exception once more:
TestException1 risen
1
